//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18063 版自动生成。
// 
#pragma warning disable 1591

namespace highsunMobileOA.com.hiooy.ERPtest {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_ERPPromiseCostAnalysisSoap", Namespace="http://dsp.hiooy.com:8201/WebServices")]
    public partial class WS_ERPPromiseCostAnalysis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ERPCOSTComConCompleteReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPCOSTComPrjConCompleteReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPCOSTComConExecReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPCOSTPrjConExecReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPCOSTAllPrjConExecReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_ERPPromiseCostAnalysis() {
            this.Url = global::highsunMobileOA.Properties.Settings.Default.highsunMobileOA_com_hiooy_ERPtest_WS_ERPPromiseCostAnalysis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ERPCOSTComConCompleteReportCompletedEventHandler ERPCOSTComConCompleteReportCompleted;
        
        /// <remarks/>
        public event ERPCOSTComPrjConCompleteReportCompletedEventHandler ERPCOSTComPrjConCompleteReportCompleted;
        
        /// <remarks/>
        public event ERPCOSTComConExecReportCompletedEventHandler ERPCOSTComConExecReportCompleted;
        
        /// <remarks/>
        public event ERPCOSTPrjConExecReportCompletedEventHandler ERPCOSTPrjConExecReportCompleted;
        
        /// <remarks/>
        public event ERPCOSTAllPrjConExecReportCompletedEventHandler ERPCOSTAllPrjConExecReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8201/WebServices/ERPCOSTComConCompleteReport", RequestNamespace="http://dsp.hiooy.com:8201/WebServices", ResponseNamespace="http://dsp.hiooy.com:8201/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPCOSTComConCompleteReport(string callKey) {
            object[] results = this.Invoke("ERPCOSTComConCompleteReport", new object[] {
                        callKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPCOSTComConCompleteReportAsync(string callKey) {
            this.ERPCOSTComConCompleteReportAsync(callKey, null);
        }
        
        /// <remarks/>
        public void ERPCOSTComConCompleteReportAsync(string callKey, object userState) {
            if ((this.ERPCOSTComConCompleteReportOperationCompleted == null)) {
                this.ERPCOSTComConCompleteReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPCOSTComConCompleteReportOperationCompleted);
            }
            this.InvokeAsync("ERPCOSTComConCompleteReport", new object[] {
                        callKey}, this.ERPCOSTComConCompleteReportOperationCompleted, userState);
        }
        
        private void OnERPCOSTComConCompleteReportOperationCompleted(object arg) {
            if ((this.ERPCOSTComConCompleteReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPCOSTComConCompleteReportCompleted(this, new ERPCOSTComConCompleteReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8201/WebServices/ERPCOSTComPrjConCompleteReport", RequestNamespace="http://dsp.hiooy.com:8201/WebServices", ResponseNamespace="http://dsp.hiooy.com:8201/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPCOSTComPrjConCompleteReport(string callKey, string companyID) {
            object[] results = this.Invoke("ERPCOSTComPrjConCompleteReport", new object[] {
                        callKey,
                        companyID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPCOSTComPrjConCompleteReportAsync(string callKey, string companyID) {
            this.ERPCOSTComPrjConCompleteReportAsync(callKey, companyID, null);
        }
        
        /// <remarks/>
        public void ERPCOSTComPrjConCompleteReportAsync(string callKey, string companyID, object userState) {
            if ((this.ERPCOSTComPrjConCompleteReportOperationCompleted == null)) {
                this.ERPCOSTComPrjConCompleteReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPCOSTComPrjConCompleteReportOperationCompleted);
            }
            this.InvokeAsync("ERPCOSTComPrjConCompleteReport", new object[] {
                        callKey,
                        companyID}, this.ERPCOSTComPrjConCompleteReportOperationCompleted, userState);
        }
        
        private void OnERPCOSTComPrjConCompleteReportOperationCompleted(object arg) {
            if ((this.ERPCOSTComPrjConCompleteReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPCOSTComPrjConCompleteReportCompleted(this, new ERPCOSTComPrjConCompleteReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8201/WebServices/ERPCOSTComConExecReport", RequestNamespace="http://dsp.hiooy.com:8201/WebServices", ResponseNamespace="http://dsp.hiooy.com:8201/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPCOSTComConExecReport(string callKey, string companyID) {
            object[] results = this.Invoke("ERPCOSTComConExecReport", new object[] {
                        callKey,
                        companyID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPCOSTComConExecReportAsync(string callKey, string companyID) {
            this.ERPCOSTComConExecReportAsync(callKey, companyID, null);
        }
        
        /// <remarks/>
        public void ERPCOSTComConExecReportAsync(string callKey, string companyID, object userState) {
            if ((this.ERPCOSTComConExecReportOperationCompleted == null)) {
                this.ERPCOSTComConExecReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPCOSTComConExecReportOperationCompleted);
            }
            this.InvokeAsync("ERPCOSTComConExecReport", new object[] {
                        callKey,
                        companyID}, this.ERPCOSTComConExecReportOperationCompleted, userState);
        }
        
        private void OnERPCOSTComConExecReportOperationCompleted(object arg) {
            if ((this.ERPCOSTComConExecReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPCOSTComConExecReportCompleted(this, new ERPCOSTComConExecReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8201/WebServices/ERPCOSTPrjConExecReport", RequestNamespace="http://dsp.hiooy.com:8201/WebServices", ResponseNamespace="http://dsp.hiooy.com:8201/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPCOSTPrjConExecReport(string callKey, string companyID) {
            object[] results = this.Invoke("ERPCOSTPrjConExecReport", new object[] {
                        callKey,
                        companyID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPCOSTPrjConExecReportAsync(string callKey, string companyID) {
            this.ERPCOSTPrjConExecReportAsync(callKey, companyID, null);
        }
        
        /// <remarks/>
        public void ERPCOSTPrjConExecReportAsync(string callKey, string companyID, object userState) {
            if ((this.ERPCOSTPrjConExecReportOperationCompleted == null)) {
                this.ERPCOSTPrjConExecReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPCOSTPrjConExecReportOperationCompleted);
            }
            this.InvokeAsync("ERPCOSTPrjConExecReport", new object[] {
                        callKey,
                        companyID}, this.ERPCOSTPrjConExecReportOperationCompleted, userState);
        }
        
        private void OnERPCOSTPrjConExecReportOperationCompleted(object arg) {
            if ((this.ERPCOSTPrjConExecReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPCOSTPrjConExecReportCompleted(this, new ERPCOSTPrjConExecReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8201/WebServices/ERPCOSTAllPrjConExecReport", RequestNamespace="http://dsp.hiooy.com:8201/WebServices", ResponseNamespace="http://dsp.hiooy.com:8201/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPCOSTAllPrjConExecReport(string callKey) {
            object[] results = this.Invoke("ERPCOSTAllPrjConExecReport", new object[] {
                        callKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPCOSTAllPrjConExecReportAsync(string callKey) {
            this.ERPCOSTAllPrjConExecReportAsync(callKey, null);
        }
        
        /// <remarks/>
        public void ERPCOSTAllPrjConExecReportAsync(string callKey, object userState) {
            if ((this.ERPCOSTAllPrjConExecReportOperationCompleted == null)) {
                this.ERPCOSTAllPrjConExecReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPCOSTAllPrjConExecReportOperationCompleted);
            }
            this.InvokeAsync("ERPCOSTAllPrjConExecReport", new object[] {
                        callKey}, this.ERPCOSTAllPrjConExecReportOperationCompleted, userState);
        }
        
        private void OnERPCOSTAllPrjConExecReportOperationCompleted(object arg) {
            if ((this.ERPCOSTAllPrjConExecReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPCOSTAllPrjConExecReportCompleted(this, new ERPCOSTAllPrjConExecReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPCOSTComConCompleteReportCompletedEventHandler(object sender, ERPCOSTComConCompleteReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPCOSTComConCompleteReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPCOSTComConCompleteReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPCOSTComPrjConCompleteReportCompletedEventHandler(object sender, ERPCOSTComPrjConCompleteReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPCOSTComPrjConCompleteReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPCOSTComPrjConCompleteReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPCOSTComConExecReportCompletedEventHandler(object sender, ERPCOSTComConExecReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPCOSTComConExecReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPCOSTComConExecReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPCOSTPrjConExecReportCompletedEventHandler(object sender, ERPCOSTPrjConExecReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPCOSTPrjConExecReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPCOSTPrjConExecReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPCOSTAllPrjConExecReportCompletedEventHandler(object sender, ERPCOSTAllPrjConExecReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPCOSTAllPrjConExecReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPCOSTAllPrjConExecReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591