//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace highsunMobileOA.com.hiooy.dsp {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_HighsunPortal1Soap", Namespace="http://dsp.hiooy.com:8200/WebServices")]
    public partial class WS_HighsunPortal1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HighsunPortal_GetCenterNewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_GetCenterNewsByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_GetCenterNewsByTypeAndIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_GetOANoticesOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LoadInsideCompetesOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_GetInsideCompeteByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LoadTrainingInfosByChannelIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_GetTrainingInfoByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LoadChannelItemsByChannelIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_GetChannelItemByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LoadCEOSpeakingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_GetCEOSpeakingOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LodaKaoqinDateByYearOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LoadKaoqinDataByDayOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LoadKaoqinDataByMonthOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LoadSalariesOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LoadSalaryByMonthOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_LoadPersonConsumeOperationCompleted;
        
        private System.Threading.SendOrPostCallback HighsunPortal_GetNiceNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_HighsunPortal1() {
            this.Url = global::highsunMobileOA.Properties.Settings.Default.highsunMobileOA_com_hiooy_dsp_WS_HighsunPortal1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HighsunPortal_GetCenterNewsCompletedEventHandler HighsunPortal_GetCenterNewsCompleted;
        
        /// <remarks/>
        public event HighsunPortal_GetCenterNewsByIDCompletedEventHandler HighsunPortal_GetCenterNewsByIDCompleted;
        
        /// <remarks/>
        public event HighsunPortal_GetCenterNewsByTypeAndIDCompletedEventHandler HighsunPortal_GetCenterNewsByTypeAndIDCompleted;
        
        /// <remarks/>
        public event HighsunPortal_GetOANoticesCompletedEventHandler HighsunPortal_GetOANoticesCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LoadInsideCompetesCompletedEventHandler HighsunPortal_LoadInsideCompetesCompleted;
        
        /// <remarks/>
        public event HighsunPortal_GetInsideCompeteByIDCompletedEventHandler HighsunPortal_GetInsideCompeteByIDCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LoadTrainingInfosByChannelIDCompletedEventHandler HighsunPortal_LoadTrainingInfosByChannelIDCompleted;
        
        /// <remarks/>
        public event HighsunPortal_GetTrainingInfoByIDCompletedEventHandler HighsunPortal_GetTrainingInfoByIDCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LoadChannelItemsByChannelIDCompletedEventHandler HighsunPortal_LoadChannelItemsByChannelIDCompleted;
        
        /// <remarks/>
        public event HighsunPortal_GetChannelItemByIDCompletedEventHandler HighsunPortal_GetChannelItemByIDCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LoadCEOSpeakingsCompletedEventHandler HighsunPortal_LoadCEOSpeakingsCompleted;
        
        /// <remarks/>
        public event HighsunPortal_GetCEOSpeakingCompletedEventHandler HighsunPortal_GetCEOSpeakingCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LodaKaoqinDateByYearCompletedEventHandler HighsunPortal_LodaKaoqinDateByYearCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LoadKaoqinDataByDayCompletedEventHandler HighsunPortal_LoadKaoqinDataByDayCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LoadKaoqinDataByMonthCompletedEventHandler HighsunPortal_LoadKaoqinDataByMonthCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LoadSalariesCompletedEventHandler HighsunPortal_LoadSalariesCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LoadSalaryByMonthCompletedEventHandler HighsunPortal_LoadSalaryByMonthCompleted;
        
        /// <remarks/>
        public event HighsunPortal_LoadPersonConsumeCompletedEventHandler HighsunPortal_LoadPersonConsumeCompleted;
        
        /// <remarks/>
        public event HighsunPortal_GetNiceNameCompletedEventHandler HighsunPortal_GetNiceNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_GetCenterNews", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_GetCenterNews(string callKey, string newsType, int topNum) {
            object[] results = this.Invoke("HighsunPortal_GetCenterNews", new object[] {
                        callKey,
                        newsType,
                        topNum});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_GetCenterNewsAsync(string callKey, string newsType, int topNum) {
            this.HighsunPortal_GetCenterNewsAsync(callKey, newsType, topNum, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_GetCenterNewsAsync(string callKey, string newsType, int topNum, object userState) {
            if ((this.HighsunPortal_GetCenterNewsOperationCompleted == null)) {
                this.HighsunPortal_GetCenterNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_GetCenterNewsOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_GetCenterNews", new object[] {
                        callKey,
                        newsType,
                        topNum}, this.HighsunPortal_GetCenterNewsOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_GetCenterNewsOperationCompleted(object arg) {
            if ((this.HighsunPortal_GetCenterNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_GetCenterNewsCompleted(this, new HighsunPortal_GetCenterNewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_GetCenterNewsByID", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HighsunPortal_GetCenterNewsByID(string callKey, string newsID) {
            object[] results = this.Invoke("HighsunPortal_GetCenterNewsByID", new object[] {
                        callKey,
                        newsID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_GetCenterNewsByIDAsync(string callKey, string newsID) {
            this.HighsunPortal_GetCenterNewsByIDAsync(callKey, newsID, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_GetCenterNewsByIDAsync(string callKey, string newsID, object userState) {
            if ((this.HighsunPortal_GetCenterNewsByIDOperationCompleted == null)) {
                this.HighsunPortal_GetCenterNewsByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_GetCenterNewsByIDOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_GetCenterNewsByID", new object[] {
                        callKey,
                        newsID}, this.HighsunPortal_GetCenterNewsByIDOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_GetCenterNewsByIDOperationCompleted(object arg) {
            if ((this.HighsunPortal_GetCenterNewsByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_GetCenterNewsByIDCompleted(this, new HighsunPortal_GetCenterNewsByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_GetCenterNewsByTypeAndID", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HighsunPortal_GetCenterNewsByTypeAndID(string callKey, string newsType, string newsID) {
            object[] results = this.Invoke("HighsunPortal_GetCenterNewsByTypeAndID", new object[] {
                        callKey,
                        newsType,
                        newsID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_GetCenterNewsByTypeAndIDAsync(string callKey, string newsType, string newsID) {
            this.HighsunPortal_GetCenterNewsByTypeAndIDAsync(callKey, newsType, newsID, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_GetCenterNewsByTypeAndIDAsync(string callKey, string newsType, string newsID, object userState) {
            if ((this.HighsunPortal_GetCenterNewsByTypeAndIDOperationCompleted == null)) {
                this.HighsunPortal_GetCenterNewsByTypeAndIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_GetCenterNewsByTypeAndIDOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_GetCenterNewsByTypeAndID", new object[] {
                        callKey,
                        newsType,
                        newsID}, this.HighsunPortal_GetCenterNewsByTypeAndIDOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_GetCenterNewsByTypeAndIDOperationCompleted(object arg) {
            if ((this.HighsunPortal_GetCenterNewsByTypeAndIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_GetCenterNewsByTypeAndIDCompleted(this, new HighsunPortal_GetCenterNewsByTypeAndIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_GetOANotices", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_GetOANotices(string callKey, string noticeType) {
            object[] results = this.Invoke("HighsunPortal_GetOANotices", new object[] {
                        callKey,
                        noticeType});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_GetOANoticesAsync(string callKey, string noticeType) {
            this.HighsunPortal_GetOANoticesAsync(callKey, noticeType, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_GetOANoticesAsync(string callKey, string noticeType, object userState) {
            if ((this.HighsunPortal_GetOANoticesOperationCompleted == null)) {
                this.HighsunPortal_GetOANoticesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_GetOANoticesOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_GetOANotices", new object[] {
                        callKey,
                        noticeType}, this.HighsunPortal_GetOANoticesOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_GetOANoticesOperationCompleted(object arg) {
            if ((this.HighsunPortal_GetOANoticesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_GetOANoticesCompleted(this, new HighsunPortal_GetOANoticesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LoadInsideCompetes", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_LoadInsideCompetes(string callKey, int topNum) {
            object[] results = this.Invoke("HighsunPortal_LoadInsideCompetes", new object[] {
                        callKey,
                        topNum});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadInsideCompetesAsync(string callKey, int topNum) {
            this.HighsunPortal_LoadInsideCompetesAsync(callKey, topNum, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadInsideCompetesAsync(string callKey, int topNum, object userState) {
            if ((this.HighsunPortal_LoadInsideCompetesOperationCompleted == null)) {
                this.HighsunPortal_LoadInsideCompetesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LoadInsideCompetesOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LoadInsideCompetes", new object[] {
                        callKey,
                        topNum}, this.HighsunPortal_LoadInsideCompetesOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LoadInsideCompetesOperationCompleted(object arg) {
            if ((this.HighsunPortal_LoadInsideCompetesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LoadInsideCompetesCompleted(this, new HighsunPortal_LoadInsideCompetesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_GetInsideCompeteByID", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HighsunPortal_GetInsideCompeteByID(string callKey, int competeID) {
            object[] results = this.Invoke("HighsunPortal_GetInsideCompeteByID", new object[] {
                        callKey,
                        competeID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_GetInsideCompeteByIDAsync(string callKey, int competeID) {
            this.HighsunPortal_GetInsideCompeteByIDAsync(callKey, competeID, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_GetInsideCompeteByIDAsync(string callKey, int competeID, object userState) {
            if ((this.HighsunPortal_GetInsideCompeteByIDOperationCompleted == null)) {
                this.HighsunPortal_GetInsideCompeteByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_GetInsideCompeteByIDOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_GetInsideCompeteByID", new object[] {
                        callKey,
                        competeID}, this.HighsunPortal_GetInsideCompeteByIDOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_GetInsideCompeteByIDOperationCompleted(object arg) {
            if ((this.HighsunPortal_GetInsideCompeteByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_GetInsideCompeteByIDCompleted(this, new HighsunPortal_GetInsideCompeteByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LoadTrainingInfosByChannelID", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_LoadTrainingInfosByChannelID(string callKey, string channelID, int topNum) {
            object[] results = this.Invoke("HighsunPortal_LoadTrainingInfosByChannelID", new object[] {
                        callKey,
                        channelID,
                        topNum});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadTrainingInfosByChannelIDAsync(string callKey, string channelID, int topNum) {
            this.HighsunPortal_LoadTrainingInfosByChannelIDAsync(callKey, channelID, topNum, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadTrainingInfosByChannelIDAsync(string callKey, string channelID, int topNum, object userState) {
            if ((this.HighsunPortal_LoadTrainingInfosByChannelIDOperationCompleted == null)) {
                this.HighsunPortal_LoadTrainingInfosByChannelIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LoadTrainingInfosByChannelIDOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LoadTrainingInfosByChannelID", new object[] {
                        callKey,
                        channelID,
                        topNum}, this.HighsunPortal_LoadTrainingInfosByChannelIDOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LoadTrainingInfosByChannelIDOperationCompleted(object arg) {
            if ((this.HighsunPortal_LoadTrainingInfosByChannelIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LoadTrainingInfosByChannelIDCompleted(this, new HighsunPortal_LoadTrainingInfosByChannelIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_GetTrainingInfoByID", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HighsunPortal_GetTrainingInfoByID(string callKey, string itemID) {
            object[] results = this.Invoke("HighsunPortal_GetTrainingInfoByID", new object[] {
                        callKey,
                        itemID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_GetTrainingInfoByIDAsync(string callKey, string itemID) {
            this.HighsunPortal_GetTrainingInfoByIDAsync(callKey, itemID, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_GetTrainingInfoByIDAsync(string callKey, string itemID, object userState) {
            if ((this.HighsunPortal_GetTrainingInfoByIDOperationCompleted == null)) {
                this.HighsunPortal_GetTrainingInfoByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_GetTrainingInfoByIDOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_GetTrainingInfoByID", new object[] {
                        callKey,
                        itemID}, this.HighsunPortal_GetTrainingInfoByIDOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_GetTrainingInfoByIDOperationCompleted(object arg) {
            if ((this.HighsunPortal_GetTrainingInfoByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_GetTrainingInfoByIDCompleted(this, new HighsunPortal_GetTrainingInfoByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LoadChannelItemsByChannelID", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_LoadChannelItemsByChannelID(string callKey, string channelID, int numTop) {
            object[] results = this.Invoke("HighsunPortal_LoadChannelItemsByChannelID", new object[] {
                        callKey,
                        channelID,
                        numTop});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadChannelItemsByChannelIDAsync(string callKey, string channelID, int numTop) {
            this.HighsunPortal_LoadChannelItemsByChannelIDAsync(callKey, channelID, numTop, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadChannelItemsByChannelIDAsync(string callKey, string channelID, int numTop, object userState) {
            if ((this.HighsunPortal_LoadChannelItemsByChannelIDOperationCompleted == null)) {
                this.HighsunPortal_LoadChannelItemsByChannelIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LoadChannelItemsByChannelIDOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LoadChannelItemsByChannelID", new object[] {
                        callKey,
                        channelID,
                        numTop}, this.HighsunPortal_LoadChannelItemsByChannelIDOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LoadChannelItemsByChannelIDOperationCompleted(object arg) {
            if ((this.HighsunPortal_LoadChannelItemsByChannelIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LoadChannelItemsByChannelIDCompleted(this, new HighsunPortal_LoadChannelItemsByChannelIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_GetChannelItemByID", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HighsunPortal_GetChannelItemByID(string callKey, string itemID) {
            object[] results = this.Invoke("HighsunPortal_GetChannelItemByID", new object[] {
                        callKey,
                        itemID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_GetChannelItemByIDAsync(string callKey, string itemID) {
            this.HighsunPortal_GetChannelItemByIDAsync(callKey, itemID, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_GetChannelItemByIDAsync(string callKey, string itemID, object userState) {
            if ((this.HighsunPortal_GetChannelItemByIDOperationCompleted == null)) {
                this.HighsunPortal_GetChannelItemByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_GetChannelItemByIDOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_GetChannelItemByID", new object[] {
                        callKey,
                        itemID}, this.HighsunPortal_GetChannelItemByIDOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_GetChannelItemByIDOperationCompleted(object arg) {
            if ((this.HighsunPortal_GetChannelItemByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_GetChannelItemByIDCompleted(this, new HighsunPortal_GetChannelItemByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LoadCEOSpeakings", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_LoadCEOSpeakings(string callKey, int topNum) {
            object[] results = this.Invoke("HighsunPortal_LoadCEOSpeakings", new object[] {
                        callKey,
                        topNum});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadCEOSpeakingsAsync(string callKey, int topNum) {
            this.HighsunPortal_LoadCEOSpeakingsAsync(callKey, topNum, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadCEOSpeakingsAsync(string callKey, int topNum, object userState) {
            if ((this.HighsunPortal_LoadCEOSpeakingsOperationCompleted == null)) {
                this.HighsunPortal_LoadCEOSpeakingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LoadCEOSpeakingsOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LoadCEOSpeakings", new object[] {
                        callKey,
                        topNum}, this.HighsunPortal_LoadCEOSpeakingsOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LoadCEOSpeakingsOperationCompleted(object arg) {
            if ((this.HighsunPortal_LoadCEOSpeakingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LoadCEOSpeakingsCompleted(this, new HighsunPortal_LoadCEOSpeakingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_GetCEOSpeaking", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HighsunPortal_GetCEOSpeaking(string callKey, string courseID) {
            object[] results = this.Invoke("HighsunPortal_GetCEOSpeaking", new object[] {
                        callKey,
                        courseID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_GetCEOSpeakingAsync(string callKey, string courseID) {
            this.HighsunPortal_GetCEOSpeakingAsync(callKey, courseID, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_GetCEOSpeakingAsync(string callKey, string courseID, object userState) {
            if ((this.HighsunPortal_GetCEOSpeakingOperationCompleted == null)) {
                this.HighsunPortal_GetCEOSpeakingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_GetCEOSpeakingOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_GetCEOSpeaking", new object[] {
                        callKey,
                        courseID}, this.HighsunPortal_GetCEOSpeakingOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_GetCEOSpeakingOperationCompleted(object arg) {
            if ((this.HighsunPortal_GetCEOSpeakingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_GetCEOSpeakingCompleted(this, new HighsunPortal_GetCEOSpeakingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LodaKaoqinDateByYear", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_LodaKaoqinDateByYear(string callKey, string name, string checkYear) {
            object[] results = this.Invoke("HighsunPortal_LodaKaoqinDateByYear", new object[] {
                        callKey,
                        name,
                        checkYear});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LodaKaoqinDateByYearAsync(string callKey, string name, string checkYear) {
            this.HighsunPortal_LodaKaoqinDateByYearAsync(callKey, name, checkYear, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LodaKaoqinDateByYearAsync(string callKey, string name, string checkYear, object userState) {
            if ((this.HighsunPortal_LodaKaoqinDateByYearOperationCompleted == null)) {
                this.HighsunPortal_LodaKaoqinDateByYearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LodaKaoqinDateByYearOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LodaKaoqinDateByYear", new object[] {
                        callKey,
                        name,
                        checkYear}, this.HighsunPortal_LodaKaoqinDateByYearOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LodaKaoqinDateByYearOperationCompleted(object arg) {
            if ((this.HighsunPortal_LodaKaoqinDateByYearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LodaKaoqinDateByYearCompleted(this, new HighsunPortal_LodaKaoqinDateByYearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LoadKaoqinDataByDay", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HighsunPortal_LoadKaoqinDataByDay(string callKey, string name, string checkYear, string checkMonth, string checkDay) {
            object[] results = this.Invoke("HighsunPortal_LoadKaoqinDataByDay", new object[] {
                        callKey,
                        name,
                        checkYear,
                        checkMonth,
                        checkDay});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadKaoqinDataByDayAsync(string callKey, string name, string checkYear, string checkMonth, string checkDay) {
            this.HighsunPortal_LoadKaoqinDataByDayAsync(callKey, name, checkYear, checkMonth, checkDay, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadKaoqinDataByDayAsync(string callKey, string name, string checkYear, string checkMonth, string checkDay, object userState) {
            if ((this.HighsunPortal_LoadKaoqinDataByDayOperationCompleted == null)) {
                this.HighsunPortal_LoadKaoqinDataByDayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LoadKaoqinDataByDayOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LoadKaoqinDataByDay", new object[] {
                        callKey,
                        name,
                        checkYear,
                        checkMonth,
                        checkDay}, this.HighsunPortal_LoadKaoqinDataByDayOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LoadKaoqinDataByDayOperationCompleted(object arg) {
            if ((this.HighsunPortal_LoadKaoqinDataByDayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LoadKaoqinDataByDayCompleted(this, new HighsunPortal_LoadKaoqinDataByDayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LoadKaoqinDataByMonth", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_LoadKaoqinDataByMonth(string callKey, string name, string checkYear, string checkMonth) {
            object[] results = this.Invoke("HighsunPortal_LoadKaoqinDataByMonth", new object[] {
                        callKey,
                        name,
                        checkYear,
                        checkMonth});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadKaoqinDataByMonthAsync(string callKey, string name, string checkYear, string checkMonth) {
            this.HighsunPortal_LoadKaoqinDataByMonthAsync(callKey, name, checkYear, checkMonth, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadKaoqinDataByMonthAsync(string callKey, string name, string checkYear, string checkMonth, object userState) {
            if ((this.HighsunPortal_LoadKaoqinDataByMonthOperationCompleted == null)) {
                this.HighsunPortal_LoadKaoqinDataByMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LoadKaoqinDataByMonthOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LoadKaoqinDataByMonth", new object[] {
                        callKey,
                        name,
                        checkYear,
                        checkMonth}, this.HighsunPortal_LoadKaoqinDataByMonthOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LoadKaoqinDataByMonthOperationCompleted(object arg) {
            if ((this.HighsunPortal_LoadKaoqinDataByMonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LoadKaoqinDataByMonthCompleted(this, new HighsunPortal_LoadKaoqinDataByMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LoadSalaries", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_LoadSalaries(string callKey, string userName, string year) {
            object[] results = this.Invoke("HighsunPortal_LoadSalaries", new object[] {
                        callKey,
                        userName,
                        year});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadSalariesAsync(string callKey, string userName, string year) {
            this.HighsunPortal_LoadSalariesAsync(callKey, userName, year, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadSalariesAsync(string callKey, string userName, string year, object userState) {
            if ((this.HighsunPortal_LoadSalariesOperationCompleted == null)) {
                this.HighsunPortal_LoadSalariesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LoadSalariesOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LoadSalaries", new object[] {
                        callKey,
                        userName,
                        year}, this.HighsunPortal_LoadSalariesOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LoadSalariesOperationCompleted(object arg) {
            if ((this.HighsunPortal_LoadSalariesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LoadSalariesCompleted(this, new HighsunPortal_LoadSalariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LoadSalaryByMonth", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HighsunPortal_LoadSalaryByMonth(string callKey, string userName, string year, string month) {
            object[] results = this.Invoke("HighsunPortal_LoadSalaryByMonth", new object[] {
                        callKey,
                        userName,
                        year,
                        month});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadSalaryByMonthAsync(string callKey, string userName, string year, string month) {
            this.HighsunPortal_LoadSalaryByMonthAsync(callKey, userName, year, month, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadSalaryByMonthAsync(string callKey, string userName, string year, string month, object userState) {
            if ((this.HighsunPortal_LoadSalaryByMonthOperationCompleted == null)) {
                this.HighsunPortal_LoadSalaryByMonthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LoadSalaryByMonthOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LoadSalaryByMonth", new object[] {
                        callKey,
                        userName,
                        year,
                        month}, this.HighsunPortal_LoadSalaryByMonthOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LoadSalaryByMonthOperationCompleted(object arg) {
            if ((this.HighsunPortal_LoadSalaryByMonthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LoadSalaryByMonthCompleted(this, new HighsunPortal_LoadSalaryByMonthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_LoadPersonConsume", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HighsunPortal_LoadPersonConsume(string callKey, string userName) {
            object[] results = this.Invoke("HighsunPortal_LoadPersonConsume", new object[] {
                        callKey,
                        userName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadPersonConsumeAsync(string callKey, string userName) {
            this.HighsunPortal_LoadPersonConsumeAsync(callKey, userName, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_LoadPersonConsumeAsync(string callKey, string userName, object userState) {
            if ((this.HighsunPortal_LoadPersonConsumeOperationCompleted == null)) {
                this.HighsunPortal_LoadPersonConsumeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_LoadPersonConsumeOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_LoadPersonConsume", new object[] {
                        callKey,
                        userName}, this.HighsunPortal_LoadPersonConsumeOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_LoadPersonConsumeOperationCompleted(object arg) {
            if ((this.HighsunPortal_LoadPersonConsumeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_LoadPersonConsumeCompleted(this, new HighsunPortal_LoadPersonConsumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/HighsunPortal_GetNiceName", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HighsunPortal_GetNiceName(string UserName, string PassWord) {
            object[] results = this.Invoke("HighsunPortal_GetNiceName", new object[] {
                        UserName,
                        PassWord});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HighsunPortal_GetNiceNameAsync(string UserName, string PassWord) {
            this.HighsunPortal_GetNiceNameAsync(UserName, PassWord, null);
        }
        
        /// <remarks/>
        public void HighsunPortal_GetNiceNameAsync(string UserName, string PassWord, object userState) {
            if ((this.HighsunPortal_GetNiceNameOperationCompleted == null)) {
                this.HighsunPortal_GetNiceNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHighsunPortal_GetNiceNameOperationCompleted);
            }
            this.InvokeAsync("HighsunPortal_GetNiceName", new object[] {
                        UserName,
                        PassWord}, this.HighsunPortal_GetNiceNameOperationCompleted, userState);
        }
        
        private void OnHighsunPortal_GetNiceNameOperationCompleted(object arg) {
            if ((this.HighsunPortal_GetNiceNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HighsunPortal_GetNiceNameCompleted(this, new HighsunPortal_GetNiceNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_GetCenterNewsCompletedEventHandler(object sender, HighsunPortal_GetCenterNewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_GetCenterNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_GetCenterNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_GetCenterNewsByIDCompletedEventHandler(object sender, HighsunPortal_GetCenterNewsByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_GetCenterNewsByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_GetCenterNewsByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_GetCenterNewsByTypeAndIDCompletedEventHandler(object sender, HighsunPortal_GetCenterNewsByTypeAndIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_GetCenterNewsByTypeAndIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_GetCenterNewsByTypeAndIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_GetOANoticesCompletedEventHandler(object sender, HighsunPortal_GetOANoticesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_GetOANoticesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_GetOANoticesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LoadInsideCompetesCompletedEventHandler(object sender, HighsunPortal_LoadInsideCompetesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LoadInsideCompetesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LoadInsideCompetesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_GetInsideCompeteByIDCompletedEventHandler(object sender, HighsunPortal_GetInsideCompeteByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_GetInsideCompeteByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_GetInsideCompeteByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LoadTrainingInfosByChannelIDCompletedEventHandler(object sender, HighsunPortal_LoadTrainingInfosByChannelIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LoadTrainingInfosByChannelIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LoadTrainingInfosByChannelIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_GetTrainingInfoByIDCompletedEventHandler(object sender, HighsunPortal_GetTrainingInfoByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_GetTrainingInfoByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_GetTrainingInfoByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LoadChannelItemsByChannelIDCompletedEventHandler(object sender, HighsunPortal_LoadChannelItemsByChannelIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LoadChannelItemsByChannelIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LoadChannelItemsByChannelIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_GetChannelItemByIDCompletedEventHandler(object sender, HighsunPortal_GetChannelItemByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_GetChannelItemByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_GetChannelItemByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LoadCEOSpeakingsCompletedEventHandler(object sender, HighsunPortal_LoadCEOSpeakingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LoadCEOSpeakingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LoadCEOSpeakingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_GetCEOSpeakingCompletedEventHandler(object sender, HighsunPortal_GetCEOSpeakingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_GetCEOSpeakingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_GetCEOSpeakingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LodaKaoqinDateByYearCompletedEventHandler(object sender, HighsunPortal_LodaKaoqinDateByYearCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LodaKaoqinDateByYearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LodaKaoqinDateByYearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LoadKaoqinDataByDayCompletedEventHandler(object sender, HighsunPortal_LoadKaoqinDataByDayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LoadKaoqinDataByDayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LoadKaoqinDataByDayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LoadKaoqinDataByMonthCompletedEventHandler(object sender, HighsunPortal_LoadKaoqinDataByMonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LoadKaoqinDataByMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LoadKaoqinDataByMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LoadSalariesCompletedEventHandler(object sender, HighsunPortal_LoadSalariesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LoadSalariesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LoadSalariesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LoadSalaryByMonthCompletedEventHandler(object sender, HighsunPortal_LoadSalaryByMonthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LoadSalaryByMonthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LoadSalaryByMonthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_LoadPersonConsumeCompletedEventHandler(object sender, HighsunPortal_LoadPersonConsumeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_LoadPersonConsumeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_LoadPersonConsumeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HighsunPortal_GetNiceNameCompletedEventHandler(object sender, HighsunPortal_GetNiceNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HighsunPortal_GetNiceNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HighsunPortal_GetNiceNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591