//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18063 版自动生成。
// 
#pragma warning disable 1591

namespace highsunMobileOA.com.hiooy.canyin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_CanYingAnalysisSoap", Namespace="http://dsp.hiooy.com:8200/WebServices")]
    public partial class WS_CanYingAnalysis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CYAnalysisDayReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback CYAnalysisMonthReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback CYAnalysisYearReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback CYAnalysisSeasonReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_CanYingAnalysis() {
            this.Url = global::highsunMobileOA.Properties.Settings.Default.highsunMobileOA_com_hiooy_canyin_WS_CanYingAnalysis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CYAnalysisDayReportCompletedEventHandler CYAnalysisDayReportCompleted;
        
        /// <remarks/>
        public event CYAnalysisMonthReportCompletedEventHandler CYAnalysisMonthReportCompleted;
        
        /// <remarks/>
        public event CYAnalysisYearReportCompletedEventHandler CYAnalysisYearReportCompleted;
        
        /// <remarks/>
        public event CYAnalysisSeasonReportCompletedEventHandler CYAnalysisSeasonReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/CYAnalysisDayReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CYAnalysisDayReport(string callKey, string date) {
            object[] results = this.Invoke("CYAnalysisDayReport", new object[] {
                        callKey,
                        date});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CYAnalysisDayReportAsync(string callKey, string date) {
            this.CYAnalysisDayReportAsync(callKey, date, null);
        }
        
        /// <remarks/>
        public void CYAnalysisDayReportAsync(string callKey, string date, object userState) {
            if ((this.CYAnalysisDayReportOperationCompleted == null)) {
                this.CYAnalysisDayReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCYAnalysisDayReportOperationCompleted);
            }
            this.InvokeAsync("CYAnalysisDayReport", new object[] {
                        callKey,
                        date}, this.CYAnalysisDayReportOperationCompleted, userState);
        }
        
        private void OnCYAnalysisDayReportOperationCompleted(object arg) {
            if ((this.CYAnalysisDayReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CYAnalysisDayReportCompleted(this, new CYAnalysisDayReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/CYAnalysisMonthReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CYAnalysisMonthReport(string callKey, string year, string month) {
            object[] results = this.Invoke("CYAnalysisMonthReport", new object[] {
                        callKey,
                        year,
                        month});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CYAnalysisMonthReportAsync(string callKey, string year, string month) {
            this.CYAnalysisMonthReportAsync(callKey, year, month, null);
        }
        
        /// <remarks/>
        public void CYAnalysisMonthReportAsync(string callKey, string year, string month, object userState) {
            if ((this.CYAnalysisMonthReportOperationCompleted == null)) {
                this.CYAnalysisMonthReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCYAnalysisMonthReportOperationCompleted);
            }
            this.InvokeAsync("CYAnalysisMonthReport", new object[] {
                        callKey,
                        year,
                        month}, this.CYAnalysisMonthReportOperationCompleted, userState);
        }
        
        private void OnCYAnalysisMonthReportOperationCompleted(object arg) {
            if ((this.CYAnalysisMonthReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CYAnalysisMonthReportCompleted(this, new CYAnalysisMonthReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/CYAnalysisYearReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CYAnalysisYearReport(string callKey, string year) {
            object[] results = this.Invoke("CYAnalysisYearReport", new object[] {
                        callKey,
                        year});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CYAnalysisYearReportAsync(string callKey, string year) {
            this.CYAnalysisYearReportAsync(callKey, year, null);
        }
        
        /// <remarks/>
        public void CYAnalysisYearReportAsync(string callKey, string year, object userState) {
            if ((this.CYAnalysisYearReportOperationCompleted == null)) {
                this.CYAnalysisYearReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCYAnalysisYearReportOperationCompleted);
            }
            this.InvokeAsync("CYAnalysisYearReport", new object[] {
                        callKey,
                        year}, this.CYAnalysisYearReportOperationCompleted, userState);
        }
        
        private void OnCYAnalysisYearReportOperationCompleted(object arg) {
            if ((this.CYAnalysisYearReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CYAnalysisYearReportCompleted(this, new CYAnalysisYearReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/CYAnalysisSeasonReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CYAnalysisSeasonReport(string callKey, string year, int season) {
            object[] results = this.Invoke("CYAnalysisSeasonReport", new object[] {
                        callKey,
                        year,
                        season});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CYAnalysisSeasonReportAsync(string callKey, string year, int season) {
            this.CYAnalysisSeasonReportAsync(callKey, year, season, null);
        }
        
        /// <remarks/>
        public void CYAnalysisSeasonReportAsync(string callKey, string year, int season, object userState) {
            if ((this.CYAnalysisSeasonReportOperationCompleted == null)) {
                this.CYAnalysisSeasonReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCYAnalysisSeasonReportOperationCompleted);
            }
            this.InvokeAsync("CYAnalysisSeasonReport", new object[] {
                        callKey,
                        year,
                        season}, this.CYAnalysisSeasonReportOperationCompleted, userState);
        }
        
        private void OnCYAnalysisSeasonReportOperationCompleted(object arg) {
            if ((this.CYAnalysisSeasonReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CYAnalysisSeasonReportCompleted(this, new CYAnalysisSeasonReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CYAnalysisDayReportCompletedEventHandler(object sender, CYAnalysisDayReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CYAnalysisDayReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CYAnalysisDayReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CYAnalysisMonthReportCompletedEventHandler(object sender, CYAnalysisMonthReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CYAnalysisMonthReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CYAnalysisMonthReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CYAnalysisYearReportCompletedEventHandler(object sender, CYAnalysisYearReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CYAnalysisYearReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CYAnalysisYearReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CYAnalysisSeasonReportCompletedEventHandler(object sender, CYAnalysisSeasonReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CYAnalysisSeasonReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CYAnalysisSeasonReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591