//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18063 版自动生成。
// 
#pragma warning disable 1591

namespace highsunMobileOA.com.hiooy.ERPhouse {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_ERPSellHouseAnalysisSoap", Namespace="http://dsp.hiooy.com:8200/WebServices")]
    public partial class WS_ERPSellHouseAnalysis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ERPSellHouseAnalysisReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHouseAnlysisByProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHouseAnlysisBuildingReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHouseCWAnlysisiReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHouseSignedAnlysisReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHousePurchaseDateReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHousePurchaseDateDetailReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHouseClueAnalysisReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHouseClueDetailAnalysisReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHouseClueDayReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback ERPSellHouseClueDetailDayReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_ERPSellHouseAnalysis() {
            this.Url = global::highsunMobileOA.Properties.Settings.Default.highsunMobileOA_com_hiooy_dsp_fangdichan_WS_ERPSellHouseAnalysis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ERPSellHouseAnalysisReportCompletedEventHandler ERPSellHouseAnalysisReportCompleted;
        
        /// <remarks/>
        public event ERPSellHouseAnlysisByProjectCompletedEventHandler ERPSellHouseAnlysisByProjectCompleted;
        
        /// <remarks/>
        public event ERPSellHouseAnlysisBuildingReportCompletedEventHandler ERPSellHouseAnlysisBuildingReportCompleted;
        
        /// <remarks/>
        public event ERPSellHouseCWAnlysisiReportCompletedEventHandler ERPSellHouseCWAnlysisiReportCompleted;
        
        /// <remarks/>
        public event ERPSellHouseSignedAnlysisReportCompletedEventHandler ERPSellHouseSignedAnlysisReportCompleted;
        
        /// <remarks/>
        public event ERPSellHousePurchaseDateReportCompletedEventHandler ERPSellHousePurchaseDateReportCompleted;
        
        /// <remarks/>
        public event ERPSellHousePurchaseDateDetailReportCompletedEventHandler ERPSellHousePurchaseDateDetailReportCompleted;
        
        /// <remarks/>
        public event ERPSellHouseClueAnalysisReportCompletedEventHandler ERPSellHouseClueAnalysisReportCompleted;
        
        /// <remarks/>
        public event ERPSellHouseClueDetailAnalysisReportCompletedEventHandler ERPSellHouseClueDetailAnalysisReportCompleted;
        
        /// <remarks/>
        public event ERPSellHouseClueDayReportCompletedEventHandler ERPSellHouseClueDayReportCompleted;
        
        /// <remarks/>
        public event ERPSellHouseClueDetailDayReportCompletedEventHandler ERPSellHouseClueDetailDayReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHouseAnalysisReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHouseAnalysisReport(string callKey) {
            object[] results = this.Invoke("ERPSellHouseAnalysisReport", new object[] {
                        callKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHouseAnalysisReportAsync(string callKey) {
            this.ERPSellHouseAnalysisReportAsync(callKey, null);
        }
        
        /// <remarks/>
        public void ERPSellHouseAnalysisReportAsync(string callKey, object userState) {
            if ((this.ERPSellHouseAnalysisReportOperationCompleted == null)) {
                this.ERPSellHouseAnalysisReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHouseAnalysisReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHouseAnalysisReport", new object[] {
                        callKey}, this.ERPSellHouseAnalysisReportOperationCompleted, userState);
        }
        
        private void OnERPSellHouseAnalysisReportOperationCompleted(object arg) {
            if ((this.ERPSellHouseAnalysisReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHouseAnalysisReportCompleted(this, new ERPSellHouseAnalysisReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHouseAnlysisByProject", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHouseAnlysisByProject(string callKey, string projectNo) {
            object[] results = this.Invoke("ERPSellHouseAnlysisByProject", new object[] {
                        callKey,
                        projectNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHouseAnlysisByProjectAsync(string callKey, string projectNo) {
            this.ERPSellHouseAnlysisByProjectAsync(callKey, projectNo, null);
        }
        
        /// <remarks/>
        public void ERPSellHouseAnlysisByProjectAsync(string callKey, string projectNo, object userState) {
            if ((this.ERPSellHouseAnlysisByProjectOperationCompleted == null)) {
                this.ERPSellHouseAnlysisByProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHouseAnlysisByProjectOperationCompleted);
            }
            this.InvokeAsync("ERPSellHouseAnlysisByProject", new object[] {
                        callKey,
                        projectNo}, this.ERPSellHouseAnlysisByProjectOperationCompleted, userState);
        }
        
        private void OnERPSellHouseAnlysisByProjectOperationCompleted(object arg) {
            if ((this.ERPSellHouseAnlysisByProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHouseAnlysisByProjectCompleted(this, new ERPSellHouseAnlysisByProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHouseAnlysisBuildingReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHouseAnlysisBuildingReport(string callKey, string projectNo) {
            object[] results = this.Invoke("ERPSellHouseAnlysisBuildingReport", new object[] {
                        callKey,
                        projectNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHouseAnlysisBuildingReportAsync(string callKey, string projectNo) {
            this.ERPSellHouseAnlysisBuildingReportAsync(callKey, projectNo, null);
        }
        
        /// <remarks/>
        public void ERPSellHouseAnlysisBuildingReportAsync(string callKey, string projectNo, object userState) {
            if ((this.ERPSellHouseAnlysisBuildingReportOperationCompleted == null)) {
                this.ERPSellHouseAnlysisBuildingReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHouseAnlysisBuildingReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHouseAnlysisBuildingReport", new object[] {
                        callKey,
                        projectNo}, this.ERPSellHouseAnlysisBuildingReportOperationCompleted, userState);
        }
        
        private void OnERPSellHouseAnlysisBuildingReportOperationCompleted(object arg) {
            if ((this.ERPSellHouseAnlysisBuildingReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHouseAnlysisBuildingReportCompleted(this, new ERPSellHouseAnlysisBuildingReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHouseCWAnlysisiReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHouseCWAnlysisiReport(string callKey) {
            object[] results = this.Invoke("ERPSellHouseCWAnlysisiReport", new object[] {
                        callKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHouseCWAnlysisiReportAsync(string callKey) {
            this.ERPSellHouseCWAnlysisiReportAsync(callKey, null);
        }
        
        /// <remarks/>
        public void ERPSellHouseCWAnlysisiReportAsync(string callKey, object userState) {
            if ((this.ERPSellHouseCWAnlysisiReportOperationCompleted == null)) {
                this.ERPSellHouseCWAnlysisiReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHouseCWAnlysisiReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHouseCWAnlysisiReport", new object[] {
                        callKey}, this.ERPSellHouseCWAnlysisiReportOperationCompleted, userState);
        }
        
        private void OnERPSellHouseCWAnlysisiReportOperationCompleted(object arg) {
            if ((this.ERPSellHouseCWAnlysisiReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHouseCWAnlysisiReportCompleted(this, new ERPSellHouseCWAnlysisiReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHouseSignedAnlysisReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHouseSignedAnlysisReport(string callKey) {
            object[] results = this.Invoke("ERPSellHouseSignedAnlysisReport", new object[] {
                        callKey});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHouseSignedAnlysisReportAsync(string callKey) {
            this.ERPSellHouseSignedAnlysisReportAsync(callKey, null);
        }
        
        /// <remarks/>
        public void ERPSellHouseSignedAnlysisReportAsync(string callKey, object userState) {
            if ((this.ERPSellHouseSignedAnlysisReportOperationCompleted == null)) {
                this.ERPSellHouseSignedAnlysisReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHouseSignedAnlysisReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHouseSignedAnlysisReport", new object[] {
                        callKey}, this.ERPSellHouseSignedAnlysisReportOperationCompleted, userState);
        }
        
        private void OnERPSellHouseSignedAnlysisReportOperationCompleted(object arg) {
            if ((this.ERPSellHouseSignedAnlysisReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHouseSignedAnlysisReportCompleted(this, new ERPSellHouseSignedAnlysisReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHousePurchaseDateReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHousePurchaseDateReport(string callKey, string dateStart, string dateEnd) {
            object[] results = this.Invoke("ERPSellHousePurchaseDateReport", new object[] {
                        callKey,
                        dateStart,
                        dateEnd});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHousePurchaseDateReportAsync(string callKey, string dateStart, string dateEnd) {
            this.ERPSellHousePurchaseDateReportAsync(callKey, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void ERPSellHousePurchaseDateReportAsync(string callKey, string dateStart, string dateEnd, object userState) {
            if ((this.ERPSellHousePurchaseDateReportOperationCompleted == null)) {
                this.ERPSellHousePurchaseDateReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHousePurchaseDateReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHousePurchaseDateReport", new object[] {
                        callKey,
                        dateStart,
                        dateEnd}, this.ERPSellHousePurchaseDateReportOperationCompleted, userState);
        }
        
        private void OnERPSellHousePurchaseDateReportOperationCompleted(object arg) {
            if ((this.ERPSellHousePurchaseDateReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHousePurchaseDateReportCompleted(this, new ERPSellHousePurchaseDateReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHousePurchaseDateDetailReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHousePurchaseDateDetailReport(string callKey, string projectID, string dateStart, string dateEnd) {
            object[] results = this.Invoke("ERPSellHousePurchaseDateDetailReport", new object[] {
                        callKey,
                        projectID,
                        dateStart,
                        dateEnd});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHousePurchaseDateDetailReportAsync(string callKey, string projectID, string dateStart, string dateEnd) {
            this.ERPSellHousePurchaseDateDetailReportAsync(callKey, projectID, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void ERPSellHousePurchaseDateDetailReportAsync(string callKey, string projectID, string dateStart, string dateEnd, object userState) {
            if ((this.ERPSellHousePurchaseDateDetailReportOperationCompleted == null)) {
                this.ERPSellHousePurchaseDateDetailReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHousePurchaseDateDetailReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHousePurchaseDateDetailReport", new object[] {
                        callKey,
                        projectID,
                        dateStart,
                        dateEnd}, this.ERPSellHousePurchaseDateDetailReportOperationCompleted, userState);
        }
        
        private void OnERPSellHousePurchaseDateDetailReportOperationCompleted(object arg) {
            if ((this.ERPSellHousePurchaseDateDetailReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHousePurchaseDateDetailReportCompleted(this, new ERPSellHousePurchaseDateDetailReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHouseClueAnalysisReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHouseClueAnalysisReport(string callKey, string startDate, string endDate) {
            object[] results = this.Invoke("ERPSellHouseClueAnalysisReport", new object[] {
                        callKey,
                        startDate,
                        endDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHouseClueAnalysisReportAsync(string callKey, string startDate, string endDate) {
            this.ERPSellHouseClueAnalysisReportAsync(callKey, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void ERPSellHouseClueAnalysisReportAsync(string callKey, string startDate, string endDate, object userState) {
            if ((this.ERPSellHouseClueAnalysisReportOperationCompleted == null)) {
                this.ERPSellHouseClueAnalysisReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHouseClueAnalysisReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHouseClueAnalysisReport", new object[] {
                        callKey,
                        startDate,
                        endDate}, this.ERPSellHouseClueAnalysisReportOperationCompleted, userState);
        }
        
        private void OnERPSellHouseClueAnalysisReportOperationCompleted(object arg) {
            if ((this.ERPSellHouseClueAnalysisReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHouseClueAnalysisReportCompleted(this, new ERPSellHouseClueAnalysisReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHouseClueDetailAnalysisReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHouseClueDetailAnalysisReport(string callKey, string projectID, string dateStart, string dateEnd) {
            object[] results = this.Invoke("ERPSellHouseClueDetailAnalysisReport", new object[] {
                        callKey,
                        projectID,
                        dateStart,
                        dateEnd});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHouseClueDetailAnalysisReportAsync(string callKey, string projectID, string dateStart, string dateEnd) {
            this.ERPSellHouseClueDetailAnalysisReportAsync(callKey, projectID, dateStart, dateEnd, null);
        }
        
        /// <remarks/>
        public void ERPSellHouseClueDetailAnalysisReportAsync(string callKey, string projectID, string dateStart, string dateEnd, object userState) {
            if ((this.ERPSellHouseClueDetailAnalysisReportOperationCompleted == null)) {
                this.ERPSellHouseClueDetailAnalysisReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHouseClueDetailAnalysisReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHouseClueDetailAnalysisReport", new object[] {
                        callKey,
                        projectID,
                        dateStart,
                        dateEnd}, this.ERPSellHouseClueDetailAnalysisReportOperationCompleted, userState);
        }
        
        private void OnERPSellHouseClueDetailAnalysisReportOperationCompleted(object arg) {
            if ((this.ERPSellHouseClueDetailAnalysisReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHouseClueDetailAnalysisReportCompleted(this, new ERPSellHouseClueDetailAnalysisReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHouseClueDayReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHouseClueDayReport(string callKey, string date) {
            object[] results = this.Invoke("ERPSellHouseClueDayReport", new object[] {
                        callKey,
                        date});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHouseClueDayReportAsync(string callKey, string date) {
            this.ERPSellHouseClueDayReportAsync(callKey, date, null);
        }
        
        /// <remarks/>
        public void ERPSellHouseClueDayReportAsync(string callKey, string date, object userState) {
            if ((this.ERPSellHouseClueDayReportOperationCompleted == null)) {
                this.ERPSellHouseClueDayReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHouseClueDayReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHouseClueDayReport", new object[] {
                        callKey,
                        date}, this.ERPSellHouseClueDayReportOperationCompleted, userState);
        }
        
        private void OnERPSellHouseClueDayReportOperationCompleted(object arg) {
            if ((this.ERPSellHouseClueDayReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHouseClueDayReportCompleted(this, new ERPSellHouseClueDayReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/ERPSellHouseClueDetailDayReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ERPSellHouseClueDetailDayReport(string callKey, string projectID, string date) {
            object[] results = this.Invoke("ERPSellHouseClueDetailDayReport", new object[] {
                        callKey,
                        projectID,
                        date});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ERPSellHouseClueDetailDayReportAsync(string callKey, string projectID, string date) {
            this.ERPSellHouseClueDetailDayReportAsync(callKey, projectID, date, null);
        }
        
        /// <remarks/>
        public void ERPSellHouseClueDetailDayReportAsync(string callKey, string projectID, string date, object userState) {
            if ((this.ERPSellHouseClueDetailDayReportOperationCompleted == null)) {
                this.ERPSellHouseClueDetailDayReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnERPSellHouseClueDetailDayReportOperationCompleted);
            }
            this.InvokeAsync("ERPSellHouseClueDetailDayReport", new object[] {
                        callKey,
                        projectID,
                        date}, this.ERPSellHouseClueDetailDayReportOperationCompleted, userState);
        }
        
        private void OnERPSellHouseClueDetailDayReportOperationCompleted(object arg) {
            if ((this.ERPSellHouseClueDetailDayReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ERPSellHouseClueDetailDayReportCompleted(this, new ERPSellHouseClueDetailDayReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHouseAnalysisReportCompletedEventHandler(object sender, ERPSellHouseAnalysisReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHouseAnalysisReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHouseAnalysisReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHouseAnlysisByProjectCompletedEventHandler(object sender, ERPSellHouseAnlysisByProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHouseAnlysisByProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHouseAnlysisByProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHouseAnlysisBuildingReportCompletedEventHandler(object sender, ERPSellHouseAnlysisBuildingReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHouseAnlysisBuildingReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHouseAnlysisBuildingReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHouseCWAnlysisiReportCompletedEventHandler(object sender, ERPSellHouseCWAnlysisiReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHouseCWAnlysisiReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHouseCWAnlysisiReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHouseSignedAnlysisReportCompletedEventHandler(object sender, ERPSellHouseSignedAnlysisReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHouseSignedAnlysisReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHouseSignedAnlysisReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHousePurchaseDateReportCompletedEventHandler(object sender, ERPSellHousePurchaseDateReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHousePurchaseDateReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHousePurchaseDateReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHousePurchaseDateDetailReportCompletedEventHandler(object sender, ERPSellHousePurchaseDateDetailReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHousePurchaseDateDetailReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHousePurchaseDateDetailReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHouseClueAnalysisReportCompletedEventHandler(object sender, ERPSellHouseClueAnalysisReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHouseClueAnalysisReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHouseClueAnalysisReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHouseClueDetailAnalysisReportCompletedEventHandler(object sender, ERPSellHouseClueDetailAnalysisReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHouseClueDetailAnalysisReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHouseClueDetailAnalysisReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHouseClueDayReportCompletedEventHandler(object sender, ERPSellHouseClueDayReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHouseClueDayReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHouseClueDayReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ERPSellHouseClueDetailDayReportCompletedEventHandler(object sender, ERPSellHouseClueDetailDayReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ERPSellHouseClueDetailDayReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ERPSellHouseClueDetailDayReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591