//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace highsunMobileOA.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IReservationService")]
    public interface IReservationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/Reservation", ReplyAction="http://tempuri.org/IReservationService/ReservationResponse")]
        string Reservation(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/CheckOut", ReplyAction="http://tempuri.org/IReservationService/CheckOutResponse")]
        string CheckOut(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/RateQuery", ReplyAction="http://tempuri.org/IReservationService/RateQueryResponse")]
        string RateQuery(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/RateQueryByCusNo", ReplyAction="http://tempuri.org/IReservationService/RateQueryByCusNoResponse")]
        string RateQueryByCusNo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetReservationDetail", ReplyAction="http://tempuri.org/IReservationService/GetReservationDetailResponse")]
        string GetReservationDetail(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/ResCancel", ReplyAction="http://tempuri.org/IReservationService/ResCancelResponse")]
        string ResCancel(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/ReservationPayment", ReplyAction="http://tempuri.org/IReservationService/ReservationPaymentResponse")]
        string ReservationPayment(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/ReserveTypeAvail", ReplyAction="http://tempuri.org/IReservationService/ReserveTypeAvailResponse")]
        string ReserveTypeAvail(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetRmrate", ReplyAction="http://tempuri.org/IReservationService/GetRmrateResponse")]
        string GetRmrate(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/SearchRoomType", ReplyAction="http://tempuri.org/IReservationService/SearchRoomTypeResponse")]
        string SearchRoomType(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/CheckCusNo", ReplyAction="http://tempuri.org/IReservationService/CheckCusNoResponse")]
        string CheckCusNo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/ReservationCashment", ReplyAction="http://tempuri.org/IReservationService/ReservationCashmentResponse")]
        string ReservationCashment(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/ReservationAccountment", ReplyAction="http://tempuri.org/IReservationService/ReservationAccountmentResponse")]
        string ReservationAccountment(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetCardnoConsumes", ReplyAction="http://tempuri.org/IReservationService/GetCardnoConsumesResponse")]
        string GetCardnoConsumes(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/DelCardnoConsumes", ReplyAction="http://tempuri.org/IReservationService/DelCardnoConsumesResponse")]
        string DelCardnoConsumes(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/ReservationAccountmentByCard", ReplyAction="http://tempuri.org/IReservationService/ReservationAccountmentByCardResponse")]
        string ReservationAccountmentByCard(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/Getdic", ReplyAction="http://tempuri.org/IReservationService/GetdicResponse")]
        string Getdic(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GuestAccountQuery", ReplyAction="http://tempuri.org/IReservationService/GuestAccountQueryResponse")]
        string GuestAccountQuery(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GuestOrderQuery", ReplyAction="http://tempuri.org/IReservationService/GuestOrderQueryResponse")]
        string GuestOrderQuery(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetRoomSta", ReplyAction="http://tempuri.org/IReservationService/GetRoomStaResponse")]
        string GetRoomSta(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetRoomFutureSta", ReplyAction="http://tempuri.org/IReservationService/GetRoomFutureStaResponse")]
        string GetRoomFutureSta(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/BalanceToAraccnt", ReplyAction="http://tempuri.org/IReservationService/BalanceToAraccntResponse")]
        string BalanceToAraccnt(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/ParamTest", ReplyAction="http://tempuri.org/IReservationService/ParamTestResponse")]
        string ParamTest(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/SelectRoomno", ReplyAction="http://tempuri.org/IReservationService/SelectRoomnoResponse")]
        string SelectRoomno(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationServiceChannel : highsunMobileOA.ServiceReference1.IReservationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationServiceClient : System.ServiceModel.ClientBase<highsunMobileOA.ServiceReference1.IReservationService>, highsunMobileOA.ServiceReference1.IReservationService {
        
        public ReservationServiceClient() {
        }
        
        public ReservationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Reservation(string xml) {
            return base.Channel.Reservation(xml);
        }
        
        public string CheckOut(string xml) {
            return base.Channel.CheckOut(xml);
        }
        
        public string RateQuery(string xml) {
            return base.Channel.RateQuery(xml);
        }
        
        public string RateQueryByCusNo(string xml) {
            return base.Channel.RateQueryByCusNo(xml);
        }
        
        public string GetReservationDetail(string xml) {
            return base.Channel.GetReservationDetail(xml);
        }
        
        public string ResCancel(string xml) {
            return base.Channel.ResCancel(xml);
        }
        
        public string ReservationPayment(string xml) {
            return base.Channel.ReservationPayment(xml);
        }
        
        public string ReserveTypeAvail(string xml) {
            return base.Channel.ReserveTypeAvail(xml);
        }
        
        public string GetRmrate(string xml) {
            return base.Channel.GetRmrate(xml);
        }
        
        public string SearchRoomType(string xml) {
            return base.Channel.SearchRoomType(xml);
        }
        
        public string CheckCusNo(string xml) {
            return base.Channel.CheckCusNo(xml);
        }
        
        public string ReservationCashment(string xml) {
            return base.Channel.ReservationCashment(xml);
        }
        
        public string ReservationAccountment(string xml) {
            return base.Channel.ReservationAccountment(xml);
        }
        
        public string GetCardnoConsumes(string xml) {
            return base.Channel.GetCardnoConsumes(xml);
        }
        
        public string DelCardnoConsumes(string xml) {
            return base.Channel.DelCardnoConsumes(xml);
        }
        
        public string ReservationAccountmentByCard(string xml) {
            return base.Channel.ReservationAccountmentByCard(xml);
        }
        
        public string Getdic(string xml) {
            return base.Channel.Getdic(xml);
        }
        
        public string GuestAccountQuery(string xml) {
            return base.Channel.GuestAccountQuery(xml);
        }
        
        public string GuestOrderQuery(string xml) {
            return base.Channel.GuestOrderQuery(xml);
        }
        
        public string GetRoomSta(string xml) {
            return base.Channel.GetRoomSta(xml);
        }
        
        public string GetRoomFutureSta(string xml) {
            return base.Channel.GetRoomFutureSta(xml);
        }
        
        public string BalanceToAraccnt(string xml) {
            return base.Channel.BalanceToAraccnt(xml);
        }
        
        public string ParamTest(string xml) {
            return base.Channel.ParamTest(xml);
        }
        
        public string SelectRoomno(string xml) {
            return base.Channel.SelectRoomno(xml);
        }
    }
}
