//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18063 版自动生成。
// 
#pragma warning disable 1591

namespace highsunMobileOA.com.hiooy.industry {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_IndustryAnalysisSoap", Namespace="http://dsp.hiooy.com:8200/WebServices")]
    public partial class WS_IndustryAnalysis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MaterialPriceAndOutputAnylysisTrendOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaterialInfomationsByFnumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaterialInfomationsByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaterialInfomationsByFmodelOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_IndustryAnalysis() {
            this.Url = global::highsunMobileOA.Properties.Settings.Default.highsunMobileOA_com_hiooy_industry_WS_IndustryAnalysis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MaterialPriceAndOutputAnylysisTrendCompletedEventHandler MaterialPriceAndOutputAnylysisTrendCompleted;
        
        /// <remarks/>
        public event MaterialInfomationsByFnumberCompletedEventHandler MaterialInfomationsByFnumberCompleted;
        
        /// <remarks/>
        public event MaterialInfomationsByNameCompletedEventHandler MaterialInfomationsByNameCompleted;
        
        /// <remarks/>
        public event MaterialInfomationsByFmodelCompletedEventHandler MaterialInfomationsByFmodelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/MaterialPriceAndOutputAnylysisTrend", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MaterialPriceAndOutputAnylysisTrend(string callKey, string dateStart, string dateEnd, string materialNumber) {
            object[] results = this.Invoke("MaterialPriceAndOutputAnylysisTrend", new object[] {
                        callKey,
                        dateStart,
                        dateEnd,
                        materialNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MaterialPriceAndOutputAnylysisTrendAsync(string callKey, string dateStart, string dateEnd, string materialNumber) {
            this.MaterialPriceAndOutputAnylysisTrendAsync(callKey, dateStart, dateEnd, materialNumber, null);
        }
        
        /// <remarks/>
        public void MaterialPriceAndOutputAnylysisTrendAsync(string callKey, string dateStart, string dateEnd, string materialNumber, object userState) {
            if ((this.MaterialPriceAndOutputAnylysisTrendOperationCompleted == null)) {
                this.MaterialPriceAndOutputAnylysisTrendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaterialPriceAndOutputAnylysisTrendOperationCompleted);
            }
            this.InvokeAsync("MaterialPriceAndOutputAnylysisTrend", new object[] {
                        callKey,
                        dateStart,
                        dateEnd,
                        materialNumber}, this.MaterialPriceAndOutputAnylysisTrendOperationCompleted, userState);
        }
        
        private void OnMaterialPriceAndOutputAnylysisTrendOperationCompleted(object arg) {
            if ((this.MaterialPriceAndOutputAnylysisTrendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaterialPriceAndOutputAnylysisTrendCompleted(this, new MaterialPriceAndOutputAnylysisTrendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/MaterialInfomationsByFnumber", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MaterialInfomationsByFnumber(string callKey, string fnumber) {
            object[] results = this.Invoke("MaterialInfomationsByFnumber", new object[] {
                        callKey,
                        fnumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MaterialInfomationsByFnumberAsync(string callKey, string fnumber) {
            this.MaterialInfomationsByFnumberAsync(callKey, fnumber, null);
        }
        
        /// <remarks/>
        public void MaterialInfomationsByFnumberAsync(string callKey, string fnumber, object userState) {
            if ((this.MaterialInfomationsByFnumberOperationCompleted == null)) {
                this.MaterialInfomationsByFnumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaterialInfomationsByFnumberOperationCompleted);
            }
            this.InvokeAsync("MaterialInfomationsByFnumber", new object[] {
                        callKey,
                        fnumber}, this.MaterialInfomationsByFnumberOperationCompleted, userState);
        }
        
        private void OnMaterialInfomationsByFnumberOperationCompleted(object arg) {
            if ((this.MaterialInfomationsByFnumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaterialInfomationsByFnumberCompleted(this, new MaterialInfomationsByFnumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/MaterialInfomationsByName", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MaterialInfomationsByName(string callKey, string fname) {
            object[] results = this.Invoke("MaterialInfomationsByName", new object[] {
                        callKey,
                        fname});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MaterialInfomationsByNameAsync(string callKey, string fname) {
            this.MaterialInfomationsByNameAsync(callKey, fname, null);
        }
        
        /// <remarks/>
        public void MaterialInfomationsByNameAsync(string callKey, string fname, object userState) {
            if ((this.MaterialInfomationsByNameOperationCompleted == null)) {
                this.MaterialInfomationsByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaterialInfomationsByNameOperationCompleted);
            }
            this.InvokeAsync("MaterialInfomationsByName", new object[] {
                        callKey,
                        fname}, this.MaterialInfomationsByNameOperationCompleted, userState);
        }
        
        private void OnMaterialInfomationsByNameOperationCompleted(object arg) {
            if ((this.MaterialInfomationsByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaterialInfomationsByNameCompleted(this, new MaterialInfomationsByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/MaterialInfomationsByFmodel", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MaterialInfomationsByFmodel(string callKey, string fmodel) {
            object[] results = this.Invoke("MaterialInfomationsByFmodel", new object[] {
                        callKey,
                        fmodel});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MaterialInfomationsByFmodelAsync(string callKey, string fmodel) {
            this.MaterialInfomationsByFmodelAsync(callKey, fmodel, null);
        }
        
        /// <remarks/>
        public void MaterialInfomationsByFmodelAsync(string callKey, string fmodel, object userState) {
            if ((this.MaterialInfomationsByFmodelOperationCompleted == null)) {
                this.MaterialInfomationsByFmodelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaterialInfomationsByFmodelOperationCompleted);
            }
            this.InvokeAsync("MaterialInfomationsByFmodel", new object[] {
                        callKey,
                        fmodel}, this.MaterialInfomationsByFmodelOperationCompleted, userState);
        }
        
        private void OnMaterialInfomationsByFmodelOperationCompleted(object arg) {
            if ((this.MaterialInfomationsByFmodelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaterialInfomationsByFmodelCompleted(this, new MaterialInfomationsByFmodelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MaterialPriceAndOutputAnylysisTrendCompletedEventHandler(object sender, MaterialPriceAndOutputAnylysisTrendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaterialPriceAndOutputAnylysisTrendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaterialPriceAndOutputAnylysisTrendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MaterialInfomationsByFnumberCompletedEventHandler(object sender, MaterialInfomationsByFnumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaterialInfomationsByFnumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaterialInfomationsByFnumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MaterialInfomationsByNameCompletedEventHandler(object sender, MaterialInfomationsByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaterialInfomationsByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaterialInfomationsByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MaterialInfomationsByFmodelCompletedEventHandler(object sender, MaterialInfomationsByFmodelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaterialInfomationsByFmodelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaterialInfomationsByFmodelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591