//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18063 版自动生成。
// 
#pragma warning disable 1591

namespace highsunMobileOA.com.hiooy.SL {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_SLTradingWaterAnalysisSoap", Namespace="http://dsp.hiooy.com:8200/WebServices")]
    public partial class WS_SLTradingWaterAnalysis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SLTadingWaterAnalysisDayReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback BHAnalysisMonthReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback BHAnalysisYearReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback BHAnalysisSeasonReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback BHAnalysis4FloorReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_SLTradingWaterAnalysis() {
            this.Url = global::highsunMobileOA.Properties.Settings.Default.highsunMobileOA_com_hiooy_SL_WS_SLTradingWaterAnalysis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SLTadingWaterAnalysisDayReportCompletedEventHandler SLTadingWaterAnalysisDayReportCompleted;
        
        /// <remarks/>
        public event BHAnalysisMonthReportCompletedEventHandler BHAnalysisMonthReportCompleted;
        
        /// <remarks/>
        public event BHAnalysisYearReportCompletedEventHandler BHAnalysisYearReportCompleted;
        
        /// <remarks/>
        public event BHAnalysisSeasonReportCompletedEventHandler BHAnalysisSeasonReportCompleted;
        
        /// <remarks/>
        public event BHAnalysis4FloorReportCompletedEventHandler BHAnalysis4FloorReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/SLTadingWaterAnalysisDayReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SLTadingWaterAnalysisDayReport(string callKey, string date) {
            object[] results = this.Invoke("SLTadingWaterAnalysisDayReport", new object[] {
                        callKey,
                        date});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SLTadingWaterAnalysisDayReportAsync(string callKey, string date) {
            this.SLTadingWaterAnalysisDayReportAsync(callKey, date, null);
        }
        
        /// <remarks/>
        public void SLTadingWaterAnalysisDayReportAsync(string callKey, string date, object userState) {
            if ((this.SLTadingWaterAnalysisDayReportOperationCompleted == null)) {
                this.SLTadingWaterAnalysisDayReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSLTadingWaterAnalysisDayReportOperationCompleted);
            }
            this.InvokeAsync("SLTadingWaterAnalysisDayReport", new object[] {
                        callKey,
                        date}, this.SLTadingWaterAnalysisDayReportOperationCompleted, userState);
        }
        
        private void OnSLTadingWaterAnalysisDayReportOperationCompleted(object arg) {
            if ((this.SLTadingWaterAnalysisDayReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SLTadingWaterAnalysisDayReportCompleted(this, new SLTadingWaterAnalysisDayReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/BHAnalysisMonthReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BHAnalysisMonthReport(string callKey, string year, string month) {
            object[] results = this.Invoke("BHAnalysisMonthReport", new object[] {
                        callKey,
                        year,
                        month});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BHAnalysisMonthReportAsync(string callKey, string year, string month) {
            this.BHAnalysisMonthReportAsync(callKey, year, month, null);
        }
        
        /// <remarks/>
        public void BHAnalysisMonthReportAsync(string callKey, string year, string month, object userState) {
            if ((this.BHAnalysisMonthReportOperationCompleted == null)) {
                this.BHAnalysisMonthReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBHAnalysisMonthReportOperationCompleted);
            }
            this.InvokeAsync("BHAnalysisMonthReport", new object[] {
                        callKey,
                        year,
                        month}, this.BHAnalysisMonthReportOperationCompleted, userState);
        }
        
        private void OnBHAnalysisMonthReportOperationCompleted(object arg) {
            if ((this.BHAnalysisMonthReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BHAnalysisMonthReportCompleted(this, new BHAnalysisMonthReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/BHAnalysisYearReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BHAnalysisYearReport(string callKey, string year) {
            object[] results = this.Invoke("BHAnalysisYearReport", new object[] {
                        callKey,
                        year});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BHAnalysisYearReportAsync(string callKey, string year) {
            this.BHAnalysisYearReportAsync(callKey, year, null);
        }
        
        /// <remarks/>
        public void BHAnalysisYearReportAsync(string callKey, string year, object userState) {
            if ((this.BHAnalysisYearReportOperationCompleted == null)) {
                this.BHAnalysisYearReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBHAnalysisYearReportOperationCompleted);
            }
            this.InvokeAsync("BHAnalysisYearReport", new object[] {
                        callKey,
                        year}, this.BHAnalysisYearReportOperationCompleted, userState);
        }
        
        private void OnBHAnalysisYearReportOperationCompleted(object arg) {
            if ((this.BHAnalysisYearReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BHAnalysisYearReportCompleted(this, new BHAnalysisYearReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/BHAnalysisSeasonReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BHAnalysisSeasonReport(string callKey, string year, int season) {
            object[] results = this.Invoke("BHAnalysisSeasonReport", new object[] {
                        callKey,
                        year,
                        season});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BHAnalysisSeasonReportAsync(string callKey, string year, int season) {
            this.BHAnalysisSeasonReportAsync(callKey, year, season, null);
        }
        
        /// <remarks/>
        public void BHAnalysisSeasonReportAsync(string callKey, string year, int season, object userState) {
            if ((this.BHAnalysisSeasonReportOperationCompleted == null)) {
                this.BHAnalysisSeasonReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBHAnalysisSeasonReportOperationCompleted);
            }
            this.InvokeAsync("BHAnalysisSeasonReport", new object[] {
                        callKey,
                        year,
                        season}, this.BHAnalysisSeasonReportOperationCompleted, userState);
        }
        
        private void OnBHAnalysisSeasonReportOperationCompleted(object arg) {
            if ((this.BHAnalysisSeasonReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BHAnalysisSeasonReportCompleted(this, new BHAnalysisSeasonReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dsp.hiooy.com:8200/WebServices/BHAnalysis4FloorReport", RequestNamespace="http://dsp.hiooy.com:8200/WebServices", ResponseNamespace="http://dsp.hiooy.com:8200/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BHAnalysis4FloorReport(string callKey, string date) {
            object[] results = this.Invoke("BHAnalysis4FloorReport", new object[] {
                        callKey,
                        date});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BHAnalysis4FloorReportAsync(string callKey, string date) {
            this.BHAnalysis4FloorReportAsync(callKey, date, null);
        }
        
        /// <remarks/>
        public void BHAnalysis4FloorReportAsync(string callKey, string date, object userState) {
            if ((this.BHAnalysis4FloorReportOperationCompleted == null)) {
                this.BHAnalysis4FloorReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBHAnalysis4FloorReportOperationCompleted);
            }
            this.InvokeAsync("BHAnalysis4FloorReport", new object[] {
                        callKey,
                        date}, this.BHAnalysis4FloorReportOperationCompleted, userState);
        }
        
        private void OnBHAnalysis4FloorReportOperationCompleted(object arg) {
            if ((this.BHAnalysis4FloorReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BHAnalysis4FloorReportCompleted(this, new BHAnalysis4FloorReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SLTadingWaterAnalysisDayReportCompletedEventHandler(object sender, SLTadingWaterAnalysisDayReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SLTadingWaterAnalysisDayReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SLTadingWaterAnalysisDayReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BHAnalysisMonthReportCompletedEventHandler(object sender, BHAnalysisMonthReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BHAnalysisMonthReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BHAnalysisMonthReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BHAnalysisYearReportCompletedEventHandler(object sender, BHAnalysisYearReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BHAnalysisYearReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BHAnalysisYearReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BHAnalysisSeasonReportCompletedEventHandler(object sender, BHAnalysisSeasonReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BHAnalysisSeasonReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BHAnalysisSeasonReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BHAnalysis4FloorReportCompletedEventHandler(object sender, BHAnalysis4FloorReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BHAnalysis4FloorReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BHAnalysis4FloorReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591